kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
  - name: Deploy via docker
    environment:
      API_ENDPOINT:
        from_secret: API_ENDPOINT
      API_KEY:
        from_secret: API_KEY
      CONTACT_EMAIL:
        from_secret: CONTACT_EMAIL
      DOMAIN_NAME:
        from_secret: DOMAIN_NAME
    commands:
      - docker-compose up -d --build --force-recreate
