version: "3"

silent: true
# output: prefixed
vars:
  ASSETS_DIR: ./src/assets
  ASSETS_FILE: styles.css

tasks:
  dev:
    deps: [cargo:dev, tw:dev]

  cargo:dev:
    cmds:
      - RUST_LOG=info cargo watch -w src -x run

  cargo:build:
    cmds:
      - cargo build --release

  tw:dev:
    cmds:
      - bunx tailwindcss -i {{.ASSETS_DIR}}/src/{{.ASSETS_FILE}} -o {{.ASSETS_DIR}}/dist/{{.ASSETS_FILE}} --watch

  tw:build:
    cmds:
      - bunx tailwindcss -i {{.ASSETS_DIR}}/src/{{.ASSETS_FILE}} -o {{.ASSETS_DIR}}/dist/{{.ASSETS_FILE}} --minify
