version: "3"

silent: true
# output: prefixed
vars:
  ASSETS_FILE: styles.css
  ASSETS_INPUT_FILE: "./src/assets/{{.ASSETS_FILE}}"
  ASSETS_OUTPUT_FILE: "./public/{{.ASSETS_FILE}}"

tasks:
  dev:
    deps: [cargo:dev, tw:dev]

  cargo:dev:
    cmds:
      - RUST_LOG=info cargo watch -w src -x run

  cargo:build:
    cmds:
      - cargo build --release

  tw:dev:
    cmds:
      - bunx tailwindcss -i {{.ASSETS_INPUT_FILE}} -o {{.ASSETS_OUTPUT_FILE}} --watch

  tw:build:
    cmds:
      - bunx tailwindcss -i {{.ASSETS_INPUT_FILE}} -o {{.ASSETS_OUTPUT_FILE}} --minify
