version: "3"

silent: true
# output: prefixed
vars:
  ASSETS_DIR: ./src/assets
  ASSETS_FILE: styles.css

tasks:
  dev:
    deps: [cargo:dev, tw:watch]

  cargo:dev:
    # prefix: "Rust"
    cmds:
      - RUST_LOG=info cargo watch -w src -x run

  tw:watch:
    # prefix: "Tailwind"
    cmds:
      - bunx tailwindcss -i {{.ASSETS_DIR}}/src/{{.ASSETS_FILE}} -o {{.ASSETS_DIR}}/dist/{{.ASSETS_FILE}} --watch
